# Generated by Django 3.0.7 on 2021-01-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('username', models.CharField(max_length=255, verbose_name='UserName')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Administrator_User',
                'verbose_name_plural': 'Administrator_Users',
            },
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('username', models.CharField(max_length=255, verbose_name='UserName')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('mobileNumber', models.CharField(max_length=255, verbose_name='Mobile_Number')),
            ],
            options={
                'verbose_name': 'Normal_User',
                'verbose_name_plural': 'Normal_Users',
            },
        ),
    ]
