# Generated by Django 3.0.7 on 2021-01-06 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoType', models.CharField(max_length=255, verbose_name='Promo_Type')),
                ('promoCode', models.IntegerField(unique=True, verbose_name='Promo_Code')),
                ('creationTime', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Creation_Time')),
                ('startTime', models.DateField(verbose_name='Start_Time')),
                ('endTime', models.DateField(verbose_name='End_Time')),
                ('promoAmount', models.IntegerField(verbose_name='Promo_Amount')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is_Active')),
                ('description', models.TextField(verbose_name='Description')),
                ('normalUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.NormalUser')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
            },
        ),
    ]
